apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-nethermind-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 900Gi
  storageClassName: hdd-standard
