apiVersion: v1
kind: PersistentVolume
metadata:
  name: hddpvc-pv
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hdd-standard
  gcePersistentDisk:
    pdName: hddpvc
    fsType: ext4
