apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lighthouse
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: pvc-83d91a74-103b-4594-aea5-a2ba7977bf6b
    fsType: ext4
