apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nethermind
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: pvc-5ebc5f5b-1b47-4a0f-9e7f-f0eb803687ba
    fsType: ext4
