apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lighthouse
  labels:
    app: lighthouse
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse
  serviceName: lighthouse-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lighthouse
    spec:
      serviceAccountName: lighthouse-service-account
      securityContext:
        fsGroup: 1000
      containers:
        - name: lighthouse
          image: sigp/lighthouse:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: p2p-tcp
              containerPort: 9000
              protocol: TCP
            - name: http-api
              containerPort: 5052
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage-lighthouse-0
