apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nethermind.fullname" . }}
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: {{ include "nethermind.replicas" . }}
  selector:
    matchLabels:
      {{- include "nethermind.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "nethermind.fullname" . }}-headless
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "nethermind.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ include "nethermind.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      initContainers:
      {{- if .Values.initContainers }}
        {{- tpl (toYaml .Values.initContainers | nindent 8) $ }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: "/data"
          command:
          {{- if gt (len .Values.customCommand) 0 }}
            {{- toYaml .Values.customCommand | nindent 12}}
          {{- else }}
            {{- include "nethermind.defaultCommand" . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: "/data"
            - name: jwt
              mountPath: "/data/jwt.hex"
              subPath: jwt.hex
              readOnly: true
          ports:
            - name: p2p-tcp
              containerPort: {{ include "nethermind.p2pPort" . }}
              protocol: TCP
            - name: p2p-udp
              containerPort: {{ include "nethermind.p2pPort" . }}
              protocol: UDP
            - name: http-rpc
              containerPort: {{ .Values.httpPort }}
              protocol: TCP
            - name: ws-rpc
              containerPort: {{ .Values.wsPort }}
              protocol: TCP
            - name: auth-rpc
              containerPort: {{ .Values.authPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: jwt
          secret:
            secretName: {{ include "nethermind.fullname" . }}-jwt
      {{- if .Values.persistence.enabled }}
        {{- if .Values.persistence.existingClaim }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
        volumeClaimTemplates:
        - metadata:
            name: storage
            annotations:
              {{- toYaml .Values.persistence.annotations | nindent 8 }}
          spec:
            accessModes:
              {{- toYaml .Values.persistence.accessModes | nindent 8 }}
            resources:
              requests:
                storage: {{ .Values.persistence.size | quote }}
            storageClassName: {{ .Values.persistence.storageClassName }}
            {{- if .Values.persistence.selector }}
            selector:
              {{- toYaml .Values.persistence.selector | nindent 8 }}
            {{- end }}
        {{- end }}
      {{- else }}
        - name: storage
          emptyDir: {}
      {{- end }}
