apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nethermind
  labels:
    app: nethermind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nethermind
  serviceName: nethermind-headless
  template:
    metadata:
      labels:
        app: nethermind
    spec:
      serviceAccountName: nethermind
      containers:
        - name: nethermind
          image: "nethermind/nethermind:latest"
          imagePullPolicy: Always
          workingDir: "/data"
          volumeMounts:
            - name: storage
              mountPath: "/data"
            - name: jwt
              mountPath: "/data/jwt.hex"
              subPath: jwt.hex
              readOnly: true
          ports:
            - name: p2p-tcp
              containerPort: 30303
              protocol: TCP
            - name: p2p-udp
              containerPort: 30303
              protocol: UDP
            - name: http-rpc
              containerPort: 8545
              protocol: TCP
            - name: ws-rpc
              containerPort: 8546
              protocol: TCP
            - name: auth-rpc
              containerPort: 8551
              protocol: TCP
            - name: metrics
              containerPort: 9545
              protocol: TCP
      volumes:
        - name: jwt
          secret:
            secretName: nethermind-jwt
        - name: storage
          persistentVolumeClaim:
            claimName: storage-nethermind-0
