name: Deploy Ethereum Nodes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          curl -sSL https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash | bash
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials blockchain-cluster --zone europe-west1-b

      - name: Deploy Nethermind
        run: |
          helm upgrade --install nethermind ethereum-helm-charts/nethermind -f nethermind-values.yaml -n default

      - name: Deploy Lighthouse
        run: |
          helm upgrade --install lighthouse ethereum-helm-charts/lighthouse -f lighthouse-values.yaml -n default
