name: Deploy Ethereum Light Node

on:
  push:
    branches:
      - main
#s
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: blockchain-cluster
          location: europe-west1-b
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Add Helm repository
        run: |
          helm repo add ethereum-helm-charts https://ethpandaops.github.io/ethereum-helm-charts
          helm repo update

      - name: Apply Persistent Volumes for Nethermind and Lighthouse
        run: |
          kubectl apply -f pv-nethermind.yaml
          kubectl apply -f pv-lighthouse.yaml

      - name: Apply PVCs for Nethermind and Lighthouse
        run: |
          kubectl apply -f pvc-lighthouse-nethermind.yaml

      - name: Deploy Nethermind
        run: |
          helm upgrade --install nethermind ethereum-helm-charts/nethermind -f nethermind-values.yaml -n default

      - name: Deploy Lighthouse
        run: |
          helm upgrade --install lighthouse ethereum-helm-charts/lighthouse -f lighthouse-values.yaml -n default
